### ISSUE TITLE
To implement smart contract for provenance

### ISSUE THREAD

**Issue by ilyabukalov** [DEX-Company/dex-chain#1]

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/DEPs/tree/master/12

**Comment by mikera** [comment]
Note that DEP12 is only for publisher declared provenance, as part of metadata, and therefore usually off chain.

Smart contract based validation of provenance requires a separate DEP, it's a different problem (more about non-repudiation, timestamping and validation than declaration)

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/dex-chain/commit/b34f0fceae9b7b6da44f14a53184932e78dcd8d1

**Comment by ilyabukalov** [comment]
https://github.com/DEX-Company/DEPs/tree/master/23
