### ISSUE TITLE
To set up own parity container with customized settings/chain parameters

### ISSUE THREAD

**Issue by ilyabukalov** [DEX-Company/dex-chain#2]

**Comment by ilyabukalov** [comment]
Should have support of Websocket provider since it would be needed in the future
https://github.com/DEX-Company/starfish-js/issues/15

**Comment by ilyabukalov** [comment]
dex/barge is patched to support web sockets
Parity container with dex chain configuration created https://github.com/DEX-Company/dex-chain/commit/82730492a3dda92e6ee9ddb54447a7a88f20b0d1
Not deployed

**Comment by billbsing** [comment]
Now running with geth instead
